Repository jix-666/jix, pull requests merged in 2020-10, with the labels that each got.

#4 Models checking
  events/models.py
Labels: help wanted

#11 Adding New event page and making users able to post event
  events/forms.py
  events/migrations/0001_initial.py
  events/migrations/0002_auto_20201015_1704.py
  events/models.py
  events/templates/events/all_events.html
  events/templates/events/index.html
  events/templates/events/main.html
  events/templates/events/nav_bar.html
  events/templates/events/new_event.html
  events/urls.py
  events/views.py
Labels: help wanted

#17 add redirect and alert message for new event
  events/templates/events/all_events.html
  events/views.py
Labels: help wanted

#18 Add category side navigation bar
  events/templates/components/event_card.html
  events/templates/components/nav_bar.html
  events/templates/components/sidenav.html
  events/templates/events/all_events.html
  events/templates/events/events_by_category.html
  events/templates/events/main.html
  events/views.py
Labels: enhancement

#19 Make title slugified when save object
  events/admin.py
  events/models.py
Labels: bug, enhancement

#22 Fix event form to add attrs in widget
  events/forms.py
  events/models.py
Labels: bug, invalid

#23 Add CRUD (Update) edit method for editing the event
  events/templates/components/event_form.html
  events/templates/events/edit_event.html
  events/templates/events/event_detail.html
  events/templates/events/new_event.html
  events/urls.py
  events/views.py
Labels: enhancement

#26 Minor improvement in user interface and fix some bug.
  events/templates/components/event_card.html
  events/templates/components/event_form.html
  events/templates/components/nav_bar.html
  events/templates/events/edit_event.html
  events/templates/events/event_detail.html
  events/templates/events/new_event.html
  events/views.py
  jix/settings.py
  jix/templates/jix/index.html
  jix/views.py
Labels: bug, enhancement, invalid

#29 Update Event Card and Index page
  events/templates/components/event_card.html
  events/templates/events/all_events.html
  events/templates/events/events_by_category.html
  events/views.py
  jix/static/jix/3535686.jpg
  jix/static/jix/people.png
  jix/templates/jix/index.html
Labels: help wanted

#31 Changed on models.
  events/forms.py
  events/models.py
  events/templates/events/edit_event.html
  events/templates/events/new_event.html
Labels: enhancement

#33 Update Report to show as table
  events/templates/components/event_card.html
  report/admin.py
  report/models.py
  report/templates/components/report_table.html
  report/templates/report/all_report.html
  report/templates/report/reports_by_category.html
  report/urls.py
  report/views.py
Labels: enhancement

#34 Delete new report page.
  report/templates/report/new_report.html
  report/urls.py
  report/views.py
Labels: bug, invalid

#36 Revert "Report from each event" because bug in event
  events/templates/events/all_events.html
  events/templates/events/event_detail.html
  events/templates/events/events_by_category.html
  events/urls.py
  events/views.py
  jix/templates/jix/index.html
  report/forms.py
  report/migrations/0002_auto_20201024_1600.py
  report/models.py
  report/templates/components/report_form.html
  report/templates/report/all_report.html
  report/templates/report/reports_by_category.html
Labels: bug, invalid

#38 Views bugs fix
  events/templates/events/event_detail.html
  events/templates/events/events_by_category.html
  events/templates/events/report_event.html
  events/urls.py
  events/views.py
  jix/templates/jix/index.html
  report/forms.py
  report/migrations/0003_auto_20201025_1708.py
  report/models.py
  report/templates/components/report_form.html
  report/templates/report/all_report.html
  report/templates/report/report_detail.html
  report/templates/report/reports_by_category.html
  report/views.py
Labels: bug, invalid
