Repository jix-666/jix, pull requests merged in 2020-11, with the labels that each got.

#45 Merge report-system to master
  .flake8
  events/admin.py
  events/apps.py
  events/forms.py
  events/migrations/0001_initial.py
  events/models.py
  events/tests.py
  events/tests/__init__.py
  events/tests/event_tests.py
  events/views.py
  jix/urls.py
  jix/views.py
  report/admin.py
  report/apps.py
  report/forms.py
  report/migrations/0001_initial.py
  report/models.py
  report/tests.py
  report/tests/__init__.py
  report/tests/test_report.py
  report/views.py
Labels: documentation, enhancement, test

#47 Merge Authentication to master
  accounts/tests.py
  accounts/tests/__init__.py
  accounts/tests/test_register.py
  accounts/tests/test_sign_in.py
  accounts/tests/test_sign_out.py
Labels: enhancement, test

#48 Implement event joining system (Completed)
  events/migrations/0001_initial.py
  events/migrations/0002_event_user.py
  events/migrations/0003_attendees.py
  events/models.py
  events/templates/events/all_events.html
  events/templates/events/event_detail.html
  events/templates/events/events_by_category.html
  events/urls.py
  events/views.py
  report/migrations/0001_initial.py
Labels: enhancement

#53 Merge user-profile to test deploy 1.0
  .gitignore
  accounts/templates/accounts/user_profile.html
  accounts/views.py
  events/migrations/0001_initial.py
  events/migrations/0002_event_user.py
  events/migrations/0003_attendees.py
  events/migrations/0004_auto_20201110_0951.py
  events/models.py
  events/templates/components/nav_bar.html
  events/templates/events/event_detail.html
  events/tests/test_delete_event.py
  events/tests/test_edit_event.py
  events/tests/test_event.py
  events/tests/test_join_event.py
  events/views.py
  jix/settings.py
  jix/urls.py
  report/migrations/0001_initial.py
  report/templates/components/report_form.html
  report/tests/test_report.py
  report/views.py
  requirements.txt
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: deployment, enhancement

#67 Merge Improved Feature to master
  .flake8
  .gitignore
  accounts/templates/accounts/login.html
  accounts/templates/accounts/user_profile.html
  events/forms.py
  events/migrations/0001_initial.py
  events/models.py
  events/templates/components/event_form.html
  events/templates/components/nav_bar.html
  events/templates/components/sidenav.html
  events/templates/events/event_detail.html
  events/templates/events/main.html
  events/tests/test_delete_event.py
  events/tests/test_edit_event.py
  events/tests/test_event.py
  events/tests/test_join_event.py
  events/views.py
  jix/settings.py
  jix/static/jix/concert.jpg
  jix/templates/jix/index.html
  jix/urls.py
  report/migrations/0001_initial.py
  report/tests/test_report.py
  requirements.txt
  users/admin.py
  users/forms.py
  users/migrations/0001_initial.py
  users/models.py
  users/signals.py
  users/static/user-icon.png
  users/templates/users/profile.html
  users/tests.py
  users/views.py
Labels: help wanted
